job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-jctest
    APP_HOSTPATH: jctest
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GCLOUD_CLUSTER: p4-development
    GOOGLE_PROJECT_ID: planet-4-151612
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-jctest
    NEWRELIC_APPNAME: P4 JCTest Development
    WP_DB_NAME: planet4-jctest_wordpress_develop
    WP_STATELESS_BUCKET: planet4-jctest-stateless-develop
  release_build_env: &release_build_env
    GOOGLE_PROJECT_ID: planet4-production
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: www-stage.p4.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: jctest
    HELM_RELEASE: planet4-jctest-release
    NEWRELIC_APPNAME: P4 JCTest Release
    WP_DB_NAME: planet4-jctest_wordpress_release
    WP_STATELESS_BUCKET: planet4-jctest-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: master.k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: jctest
    HELM_RELEASE: planet4-jctest-master
    MIN_REPLICA_COUNT: 2
    NEWRELIC_APPNAME: P4 JCTest Production
    WP_DB_NAME: planet4-jctest_wordpress_master
    WP_STATELESS_BUCKET: planet4-jctest-stateless
